version: '3.8'

services:
  website:
    build: .
    ports:
      - "3000:80"
    container_name: bootstrap-website
    restart: unless-stopped
    
  # Add other services if needed (database, redis, etc.)
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: myapp
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:
